name: Node.js CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '.github/workflows/ci-cd.yaml'
  workflow_dispatch:
jobs:
  Build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g
    - run: npm ci
    - run: chmod +x change-version.sh
    - run: npm run build:stage
    - run: sudo su -

    - name: Nexus Repo Login
      run: docker login nexus-repo.eagro.az --username ${{ secrets.NEXUS_USERNAME }} --password ${{ secrets.NEXUS_PASSWORD }}
      
    - name: Image build
      run: docker build -t nexus-repo.eagro.az/eagro-analytics:1.9 .
      
    - name: Image Push to Nexus Repo
      run: docker push nexus-repo.eagro.az/eagro-analytics:1.9
      
    - name: Set up Helm
      uses: azure/setup-helm@v1
      with:
        version: 'v3.3.1'

    - name: Install or Upgrade Chart
      run: helm upgrade --install eagro-anal-ui ./chart --namespace eagro --set image.tag=1.9
