name: Node.js CI

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  Build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install -g
    - run: npm ci
    - run: chmod +x change-version.sh
    - run: npm run build:stage
    
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: https://nexus-repo.minagro.local:443
        username: admin
        password: F78d59FrfY9R4xs5D75rVYfPBbHH
